server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://${customConfig.security.username}:${customConfig.security.password}@${customConfig.eureka.server.hostname}:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    peer-node-read-timeout-ms: 2000 #读取对等节点服务器复制的超时的时间，单位为毫秒，默认为200
spring:
  application:
    name: spring-eureka
  security:
    user:
      name: ${customConfig.security.username}
      password: ${customConfig.security.password}
management:
  endpoint:
    health:
      show-details: always #健康情况-展示全部详情，否则只展示status信息









customConfig:
  eureka:
    server: #eureka的配置
      hostname: 192.168.232.141
  security: #security的配置
    username: admin
    password: admin123




#Eureka Server在启动的时候会创建一个定时任务，默认每隔一段时间（默认为60秒）将当前清单中超时（默认为90秒）没有续约的服务剔除出去。